name: Node.js
on: [push]

env:
  CI: true
  ENCRYPTION: sha512
  MYSQL_DB: cooktak_test
  MYSQL_HOST: localhost
  MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
  MYSQL_PORT: 3307
  MYSQL_TYPE: mariadb
  MYSQL_USER: root

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: use mariadb 10
        uses: getong/mariadb-action@v1.1
        with:
          container port: ${{ env.MYSQL_PORT }}
          host port: ${{ env.MYSQL_PORT }}
          mysql root password: ${{ env.MYSQL_PASS }}
          mysql database: ${{ env.MYSQL_DB }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ matrix.node-version }}-${{ env.cache-name }}-
            ${{ runner.OS }}-build-${{ matrix.node-version }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: yarn install
        run: yarn
      - name: test
        run: yarn test
